# Generated by Django 6.0.1 on 2026-04-20 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.TextField()),
                ('bio_text', models.TextField(blank=True)),
                ('profile_image_url', models.URLField(blank=True)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.TextField()),
                ('destination', models.TextField()),
                ('pickup_time', models.DateTimeField()),
                ('request_type', models.CharField(choices=[('reservation', 'Reservation'), ('realtime', 'Real-Time')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('accepted', 'Accepted'), ('full', 'Full'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('seat_capacity', models.IntegerField(default=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_rides', to='campus_pickup.profile')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driving_rides', to='campus_pickup.profile')),
            ],
        ),
        migrations.CreateModel(
            name='RideMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus_pickup.ride')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus_pickup.profile')),
            ],
        ),
        migrations.CreateModel(
            name='RideParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus_pickup.profile')),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus_pickup.ride')),
            ],
        ),
    ]
