# Generated by Django 6.0.4 on 2026-04-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_pickup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image_url',
            field=models.ImageField(blank=True, upload_to='campus_pickup/profile_images/', verbose_name='profile image'),
        ),
    ]
