# Generated by Django 6.0.4 on 2026-04-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_pickup', '0002_alter_profile_profile_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='pickup_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
