# Generated by Django 6.0.4 on 2026-04-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_pickup', '0003_alter_ride_pickup_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='destination_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='destination_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='pickup_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='pickup_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
