# Generated by Django 6.0.1 on 2026-03-04 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0006_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='join_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
